#!/bin/dash

if [ ! -d ".pig" ]; then
    echo "pigs-branch: error: pigs repository directory .pig not found"
    exit 1
fi

current_branch=$(head -n 1 .pig/branch_list)

if [ "$1" = "" ]; then
    if [ ! -d ".pig/branch/$current_branch/commit" ]; then
        echo "pigs-branch: error: this command can not be run until after the first commit"
        exit 1
    fi
    for branches in ".pig/branch"/*; do
        basename "$branches"
    done
fi

if [ "$#" = 1 ]; then
    branch="$1"
    if [ -d ".pig/branch/$branch" ]; then
        echo "pigs-branch: error: branch '$branch' already exists"
        exit 1
    fi
    mkdir ".pig/branch/$1"
    exit 0
fi
    
if [ "$1" = "-d" ]; then
    if [ "$2" = "master" ]; then
        echo "pigs-branch: error: can not delete branch 'master': default branch"
        exit 1
    elif [ ! -d ".pig/branch/$2" ]; then
        echo "pigs-branch: error: branch '$2' doesn't exist"
        exit 1
    fi
    rm -rf ".pig/branch/$2"
    echo "Deleted branch '$2'"
    exit 0
fi